name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      
      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve
          EC2_IP=$(terraform output -raw web_ip || echo "")
          echo "EC2_IP=${EC2_IP}" >> $GITHUB_ENV
      
      - name: Debug EC2 IP
        run: echo "EC2 IP is ${{ env.EC2_IP }}"
      
      - name: Wait for instance to be ready
        run: sleep 60
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Ansible
        run: pip install ansible
      
      - name: Update Ansible inventory
        run: |
          if [ -n "${{ env.EC2_IP }}" ]; then
            sed -i "s/YOUR_EC2_IP/${{ env.EC2_IP }}/g" ansible/inventory.ini
          else
            echo "EC2 IP not available. Check Terraform output."
            exit 1
          fi
      
      - name: Run Ansible playbook
        if: env.EC2_IP != ''
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/eventify-key.pem
          chmod 600 ~/.ssh/eventify-key.pem
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
